SCREEN_WIDTH = 500
SCREEN_HEIGHT = 400

NUMBER_OF_BLOCKS_WIDE = 50
NUMBER_OF_BLOCKS_HIGH = 50
BLOCK_HEIGHT = round(SCREEN_HEIGHT/NUMBER_OF_BLOCKS_HIGH)
BLOCK_WIDTH = round(SCREEN_WIDTH/NUMBER_OF_BLOCKS_WIDE)

YELLOW = (200, 200, 20)
BLACK = (0, 0, 0)
